# File:         labels.yml
# Description:  YAML file containing all of the labels used on GitHub for the project.
---
# Types
- name: "type: bug"
  color: "ff5555"
  description: ""
- name: "type: request"
  color: "ff55ff"
  description: ""
- name: "type: question"
  color: "c74ebd"
  description: ""
- name: "type: design"
  color: "0000aa"
  description: ""
- name: "type: documentation"
  color: "1631aa"
  description: ""
- name: "type: automation"
  color: "1631aa"
  description: ""
- name: "type: feature"
  color: "5555ff"
  description: ""
- name: "type: refactor"
  color: "3ab3da"
  description: ""
- name: "type: fix"
  color: "55e7e7"
  description: ""

# Auto-release Status
- name: "autorelease: pending"
  color: "ededed"
  description: ""
- name: "autorelease: tagged"
  color: "ededed"
  description: ""

# Status
- name: "status: backlog"
  color: "ffffff"
  description: ""
- name: "status: to-do"
  color: "cccccc"
  description: ""
- name: "status: in-progress"
  color: "999999"
  description: ""
- name: "status: in-review"
  color: "666666"
  description: ""
- name: "status: done"
  color: "333333"
  description: ""
- name: "status: cancelled"
  color: "000000"
  description: ""
- name: "status: won't do"
  color: "000000"
  description: ""

# Priority
- name: "priority: needs triage"
  color: "ffffff"
  description: ""
- name: "priority: critical"
  color: "ee0000"
  description: ""
- name: "priority: high"
  color: "ffaa00"
  description: ""
- name: "priority: medium"
  color: "ffff55"
  description: ""
- name: "priority: low"
  color: "55ff55"
  description: ""
- name: "priority: very low"
  color: "00aa00"
  description: ""
- name: "priority: none"
  color: "000000"
  description: ""
