name: Bug Report
description: File a bug or issue.
title: "[Bug Report] <title>"
labels: ["Type: Bug", "Priority: Needs Triage"]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: Please provide a clear and concise description of the behavior you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Please provide a clear and concise explanation of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this configuration...
        3. Run...
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Please provide detailed information about the environment in which you're encountering the bug.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Notes & Screenshots
      description: |
        Anything else that will give us more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging the files in.
    validations:
      required: false
