name: Development Story
description: Create a new development plan for the project.
title: "[Dev Story] <version> <title>"
labels: ["Priority: Needs Triage", "Status: Backlog"]
body:
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Create a list of subtasks that need to be completed for this version to be done.
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
        - [ ] Test 1
        - [ ] Test 2
    validations:
      required: true