name: Bug Report
description: File a bug/issue
title: "Bug Report - <title>"
labels: ["Type: Bug", "Priority: None"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues for this bug.
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear and concise description of the behavior you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise explanation of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this configuration...
        3. Run...
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Detailed information about the environment in which you're encountering the bug.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Notes / Screenshots
      description: |
        Anything else that will give us more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
