name: "Feature Request"
description: "Suggest new features for the project."
title: "Feature Request - <title>"
labels: ["Type: Feature Request", "Priority: None"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request for the feature that you want to request already exists.
      options:
        - label: I have searched the existing feature requests for this feature.
          required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen. Describe the problem that this solves as well as any considered drawbacks.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Altnerative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Notes / Screenshots
      description: |
        Any additional notes or screenshots that might be helpful for describing the feature and how users will use it.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
