# File:         continuous_integration.yml
# Description:  Handles continuous integration for the project.
#               Makes use of GitHub Super Linter and pytest
#               Link: https://github.com/marketplace/actions/super-linter
---
name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
      - master
  workflow_call:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code From GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_MYPY: false
