# File:         label_update.yml
# Description:  Updates the available labels on the GitHub repository
#               Uses GitHub Labeler
#               Link: https://github.com/marketplace/actions/github-labeler

name: Update Labels

on:
  push:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Labeler
        uses: crazy-max/ghaction-github-labeler@v3
