# File:         linting.yml
# Description:  Sets up python linting using pylinter GitHub action to ensure code quality

name: Python Lint and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  pylint:
    name: pylint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [-f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Linting Code with pylint
        run: |
          pylint --rcfile=${{ github.workspace }}/.linting/.pylintrc $(git ls-files '*.py')

  flake8:
    name: flake8 Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [-f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Linting Code with flake8
        run: |
          flake8 -v --config=${{ github.workspace }}/.linting/.flake8 $(git ls-files '*.py')

  isort:
    name: isort Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
      - name: Check Imports Are Sorted
        uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt requirements-test.txt"

  black:
    name: black Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          if [-f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Linting Code with black
        run: |
          black --line-length 140 $(git ls-files '*.py') --diff
          black --line-length 140 $(git ls-files '*.py') --check

  pytest:
    name: pytest Check
    runs-on: windows-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [-f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Testing Code with pytest
        run: |
          pytest
